import re
import time
import httpx
from typing import Tuple
from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger(__name__)

MAX_ATTEMPTS = 5

SYSTEM_PROMPT = """You are a Power BI / Databricks migration expert. You will receive a complete Power Query M-Query that was auto-generated by migrating a Cognos T-SQL report to Databricks SQL.

The M-Query follows this structure:
  let
      <dynamic filter variable blocks>   -- combinedlist_*, where*, dateClause
      query = "<sql segment>" & <var> & "<sql segment>" & <var> & "<sql segment>",
      Source = Databricks.Catalogs(...),
      finalsource = Value.NativeQuery(Source, query, null, [EnableFolding = false])
  in
      finalsource

YOUR TASK — fix ALL of the following categories of issues:

── M-QUERY SYNTAX ──────────────────────────────────────────────────────────────
1. Every transition between a string literal and a variable (or variable to string literal)
   MUST have an & operator on both sides. Example of correct form:
       "...WHERE 1=1"
       & dateClause
       & " GROUP BY ..."
   A missing & is the most common generated bug — check every segment boundary.
2. The query = expression must be a single valid M concatenation chain.
   No bare string literals may appear without & connecting them to adjacent tokens.
3. All dynamic filter variables (where*, dateClause) must be defined before query =
   in the let block and must end with a comma.

── SQL CORRECTNESS (inside the query = "..." segments) ─────────────────────────
4. Every WHERE clause that is followed only by dynamic AND filters MUST have
   WHERE 1=1 as its anchor so the query is valid when all filters are empty.
   Example: "WHERE 1=1" & dateClause & wherepSiteID & wherepPlayerID
5. Every column referenced in SELECT must be defined in the subquery that produces it.
   If a column is selected in an outer query but never aliased in the inner query, add it.
6. Table aliases used in SELECT or JOIN ON must correspond to an actual FROM/JOIN entry.
   If an alias like TypeRegistry or InvRegistry is used but never joined, either:
   - remove the reference if it was a scalar subquery result already aliased, or
   - correct the column reference to use the alias that actually holds that value.
6b. Scalar subquery results aliased in an inner subquery (e.g. TypeRegistryID, InventoryRegistryID)
    must be referenced by their alias in the outer query using the subquery alias prefix
    (e.g. core_doc.TypeRegistryID), NOT by a phantom table alias that was never joined.
    Example — WRONG:  CONCAT(TypeRegistry.CodeDescription, ...) 
    Example — RIGHT:  CONCAT(core_doc.TypeRegistryID, ...)
7. Fix all Databricks SQL incompatibilities:
   - col = expr aliases → expr AS col
   - string + string concatenation → CONCAT(...)
   - ISNULL() → COALESCE()
   - GETDATE() → CURRENT_TIMESTAMP
   - TOP N → LIMIT N
   - bracket identifiers [col] → col
   - (NOLOCK) hints → remove
   - varchar(n) → STRING

── WHAT YOU MUST NOT CHANGE ────────────────────────────────────────────────────
8. Do NOT change any Databricks table references (catalog.schema.table format).
9. Do NOT remove, simplify, or rename any dynamic filter variable blocks
   (combinedlist_*, where*, dateClause). Their logic must remain intact.
10. Do NOT change the Databricks.Catalogs() connection block or Value.NativeQuery() call.
11. Do NOT change column names, join conditions, GROUP BY columns, or business logic.
12. CRITICAL: Do NOT break the SQL inside query = "..." into per-line string fragments.
    The SQL must remain as one or a few large string literals separated only at dynamic
    filter injection points (& dateClause, & whereX). 
    WRONG:  & "SELECT " & "col1 " & "FROM t "
    RIGHT:  "SELECT\ncol1\nFROM t"
12. CRITICAL: Do NOT break the SQL inside query = "..." into per-line string fragments.
    The SQL must remain as one or a few large string literals separated only at dynamic
    filter injection points (& dateClause, & whereX).
    WRONG:  & "SELECT " & "col1 " & "FROM t "
    RIGHT:  "SELECT\ncol1\nFROM t"

13. CRITICAL: Do NOT modify JOIN ON conditions. Every ON clause must preserve the exact
    original alias.column references. Never prefix a column reference with the joined
    table's alias. 
    WRONG:  ON break_down.bu.region_id = bu.region_id
    RIGHT:  ON break_down.region_id = bu.region_id

14. Dynamic filter variables (wherepSiteID, wherepPlayerID, dateClause) already contain
    their own leading ' AND ' prefix inside their M expression. Never add a hardcoded
    ' AND ' string literal between two dynamic filter variables.
    WRONG:  " & wherepSiteID & " AND " & wherepPlayerID
    RIGHT:  " & wherepSiteID & wherepPlayerID
OUTPUT RULES ───────────────────────────────────────────────────────────────────
- Return ONLY the complete corrected M-Query — the full let...in finalsource block.
- No explanation, no commentary, no markdown code fences.
- The output must be directly pasteable into Power BI Advanced Editor without modification."""


def _call_llm(messages: list) -> str:
    url = f"{settings.DATABRICKS_HOST}/serving-endpoints/{settings.DATABRICKS_LLM_ENDPOINT}/invocations"
    logger.info(f"[LLM] Calling endpoint: {url}")
    t0 = time.time()
    resp = httpx.post(
        url,
        headers={"Authorization": f"Bearer {settings.DATABRICKS_TOKEN}"},
        json={"messages": messages, "max_tokens": 8192, "temperature": 0},
        timeout=120,
    )
    logger.info(f"[LLM] Response in {time.time() - t0:.1f}s — HTTP {resp.status_code}")
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"].strip()


def _clean_llm_response(raw: str) -> str:
    raw = re.sub(r"^```[a-zA-Z]*\s*", "", raw.strip(), flags=re.I)
    raw = re.sub(r"\s*```$", "", raw.strip())
    return raw.strip()


def _validate_mquery(mquery: str) -> list[str]:
    """
    Pure structural validation of the M-Query.
    Returns a list of error strings. Empty list means no issues found.
    """
    errors = []

    # 1. Must start with let and end with finalsource
    if not re.search(r'^\s*let\b', mquery, re.IGNORECASE):
        errors.append("M-Query does not start with 'let'.")
    if not re.search(r'\bin\s+finalsource\s*$', mquery, re.IGNORECASE):
        errors.append("M-Query does not end with 'in finalsource'.")

    # 2. query = block must exist
    query_block = re.search(r'\bquery\s*=\s*\n?([\s\S]+?),\s*\n\s*Source\s*=', mquery)
    if not query_block:
        errors.append("Could not locate 'query = ...' block before 'Source ='.")
        return errors

    block = query_block.group(1)

    # 3. Check & connectivity — tokenise the query block into M tokens only.
    # Valid tokens on their own line are:
    #   "..."        — string literal (may be multi-line)
    #   & varName    — variable reference
    # We extract them in order and check every adjacent pair is connected.
    #
    # Strategy: split on lines that are ONLY & <identifier> or start a new "..."
    # We look at the raw block lines with consistent 8-space indentation.
    token_lines = []
    for line in block.splitlines():
        # Only consider lines at exactly the M concatenation indent level
        # These start with 8 spaces then either " or &
        if re.match(r'^        (?:"|\&)', line):
            token_lines.append(line.strip())

    for i, tok in enumerate(token_lines):
        if tok.startswith('"') and i > 0:
            prev = token_lines[i - 1]
            if not prev.startswith('&') and not prev.endswith('&'):
                errors.append(
                    f"Missing '&' before string segment: ...{prev[-40:]} | {tok[:60]}..."
                )

    # 4. WHERE 1=1 check — only flag WHERE clauses that are at a segment boundary,
    # i.e. the string segment ends with WHERE and the next M token is & where*/dateClause.
    # We do this by scanning the raw block for the pattern:
    #   "...WHERE "
    #   & (where\w+|dateClause)
    # without a 1=1 between them.
    boundary_where = re.findall(
        r'WHERE\s*"\s*\n\s*&\s*(where\w+|dateClause)',
        block, re.IGNORECASE
    )
    # Also catch: "WHERE " & whereX  on same line
    boundary_where += re.findall(
        r'WHERE\s+"\s*&\s*(where\w+|dateClause)',
        block, re.IGNORECASE
    )
    for var in boundary_where:
        errors.append(
            f"WHERE clause feeds directly into dynamic filter '{var}' with no '1=1' anchor. "
            f"Change to: \"WHERE 1=1\" & {var}"
        )

    # 5. All where*/dateClause variables referenced in query block must be defined in let
    referenced_vars = set(re.findall(r'&\s*(where\w+|dateClause)\b', block))
    defined_vars    = set(re.findall(r'^\s*(where\w+|dateClause)\s*=', mquery, re.MULTILINE))
    missing = referenced_vars - defined_vars
    if missing:
        errors.append(f"Variables referenced in query but not defined in let: {sorted(missing)}")

    # Add to _validate_mquery after check 5:
    sql_segments = re.findall(r'"((?:[^"\\]|\\.)*)"', block)
    full_sql = "".join(s.replace('""', '"') for s in sql_segments)

    # 6. Detect corrupted JOIN ON — pattern: alias1.alias2.col where alias2 matches a known join alias
    # This catches LLM hallucination like break_down.bu.region_id
    corrupted_joins = re.findall(
        r'\bON\s+[\w]+\.([\w]+)\.([\w]+)\s*=',
        full_sql, re.IGNORECASE
    )
    if corrupted_joins:
        for outer, col in corrupted_joins:
            errors.append(
                f"Corrupted JOIN ON condition: found three-part column reference "
                f"'<alias>.{outer}.{col}' — JOIN ON must use two-part 'alias.column' only."
            )

    # 7. Detect hardcoded AND between dynamic filter variables
    hardcoded_and = re.search(
        r'&\s*(where\w+|dateClause)\s*&\s*"\s*AND\s*"\s*&\s*(where\w+|dateClause)',
        block, re.IGNORECASE
    )
    if hardcoded_and:
        errors.append(
            "Hardcoded ' AND ' string found between two dynamic filter variables. "
            "Remove it — each where* variable already includes its own leading AND."
        )
    return errors



def validate_mquery_with_llm(mquery: str) -> Tuple[str, str, bool]:
    """
    Validate and fix the full M-Query using LLM with up to MAX_ATTEMPTS attempts.
    Each failed attempt enriches the conversation with the specific errors found,
    so the LLM has full context of what went wrong in every prior round.

    Returns (fixed_mquery, summary, success).
    """
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user",   "content": f"Fix this M-Query:\n\n{mquery}"},
    ]

    current_mquery = mquery
    attempt_log: list[str] = []  # accumulates per-attempt error summaries

    for attempt in range(1, MAX_ATTEMPTS + 1):
        logger.info(f"[MQuery Validator] Attempt {attempt}/{MAX_ATTEMPTS}")

        try:
            raw = _call_llm(messages)
            current_mquery = _clean_llm_response(raw)
            logger.info(f"[LLM] M-Query received, length: {len(current_mquery)} chars")
        except Exception as e:
            logger.error(f"[LLM] Call failed on attempt {attempt}: {e}")
            summary = _build_summary(attempt_log, success=False,
                                     final_error=f"LLM call failed: {e}")
            return current_mquery, summary, False

        errors = _validate_mquery(current_mquery)

        if not errors:
            logger.info(f"[MQuery Validator] Passed on attempt {attempt}")
            summary = _build_summary(attempt_log, success=True, attempt=attempt)
            return current_mquery, summary, True

        # Record this attempt's errors for the running log
        error_block = "\n".join(f"  - {e}" for e in errors)
        attempt_log.append(f"Attempt {attempt} errors:\n{error_block}")
        logger.info(f"[MQuery Validator] Attempt {attempt} failed with {len(errors)} error(s):\n{error_block}")

        if attempt < MAX_ATTEMPTS:
            # Enrich context: include ALL prior attempt errors + current errors
            full_history = "\n\n".join(attempt_log)
            messages += [
                {"role": "assistant", "content": current_mquery},
                {"role": "user", "content": (
                    f"Your M-Query still has issues. Here is the full validation history so far:\n\n"
                    f"{full_history}\n\n"
                    f"Fix ALL of the above errors and return the complete corrected let...in block only."
                )},
            ]

    summary = _build_summary(attempt_log, success=False)
    return current_mquery, summary, False


def _build_summary(attempt_log: list[str], success: bool,
                   attempt: int = None, final_error: str = None) -> str:
    if success:
        return (
            f"M-Query validated successfully on attempt {attempt}.\n\n"
            + ("\n\n".join(attempt_log) if attempt_log else "No errors in prior attempts.")
        )
    parts = [f"M-Query could not be validated after {MAX_ATTEMPTS} attempts."]
    if attempt_log:
        parts.append("\n\n".join(attempt_log))
    if final_error:
        parts.append(f"Final error: {final_error}")
    return "\n\n".join(parts)
