import re
import time
import httpx
from typing import Tuple
from databricks.sdk import WorkspaceClient
from databricks.sdk.service.sql import StatementState
from app.core.config import settings
from app.core.logging import get_logger

logger = get_logger(__name__)

MAX_ATTEMPTS = 5

SYSTEM_PROMPT = """You are a Power BI / Databricks migration expert. You will receive a complete Power Query M-Query that was auto-generated by migrating a Cognos T-SQL report to Databricks SQL.

The M-Query follows this structure:
  let
      <dynamic filter variable blocks>   -- combinedlist_*, where*, dateClause
      query = "<sql segment>" & <var> & "<sql segment>" & <var> & "<sql segment>",
      Source = Databricks.Catalogs(...),
      finalsource = Value.NativeQuery(Source, query, null, [EnableFolding = false])
  in
      finalsource

YOUR TASK — fix ALL of the following categories of issues:

── M-QUERY SYNTAX ──────────────────────────────────────────────────────────────
1. Every transition between a string literal and a variable (or variable to string literal)
   MUST have an & operator on both sides. Example of correct form:
       "...WHERE 1=1"
       & dateClause
       & " GROUP BY ..."
   A missing & is the most common generated bug — check every segment boundary.
2. The query = expression must be a single valid M concatenation chain.
   No bare string literals may appear without & connecting them to adjacent tokens.
3. All dynamic filter variables (where*, dateClause) must be defined before query =
   in the let block and must end with a comma.

── SQL CORRECTNESS (inside the query = "..." segments) ─────────────────────────
4. Every WHERE clause that is followed only by dynamic AND filters MUST have
   WHERE 1=1 as its anchor so the query is valid when all filters are empty.
   Example: "WHERE 1=1" & dateClause & wherepSiteID & wherepPlayerID
5. Every column referenced in SELECT must be defined in the subquery that produces it.
   If a column is selected in an outer query but never aliased in the inner query, add it.
6. Table aliases used in SELECT or JOIN ON must correspond to an actual FROM/JOIN entry.
   If an alias like TypeRegistry or InvRegistry is used but never joined, either:
   - remove the reference if it was a scalar subquery result already aliased, or
   - correct the column reference to use the alias that actually holds that value.
7. Fix all Databricks SQL incompatibilities:
   - col = expr aliases → expr AS col
   - string + string concatenation → CONCAT(...)
   - ISNULL() → COALESCE()
   - GETDATE() → CURRENT_TIMESTAMP
   - TOP N → LIMIT N
   - bracket identifiers [col] → col
   - (NOLOCK) hints → remove
   - varchar(n) → STRING

── WHAT YOU MUST NOT CHANGE ────────────────────────────────────────────────────
8. Do NOT change any Databricks table references (catalog.schema.table format).
9. Do NOT remove, simplify, or rename any dynamic filter variable blocks
   (combinedlist_*, where*, dateClause). Their logic must remain intact.
10. Do NOT change the Databricks.Catalogs() connection block or Value.NativeQuery() call.
11. Do NOT change column names, join conditions, GROUP BY columns, or business logic.

OUTPUT RULES ───────────────────────────────────────────────────────────────────
- Return ONLY the complete corrected M-Query — the full let...in finalsource block.
- No explanation, no commentary, no markdown code fences.
- The output must be directly pasteable into Power BI Advanced Editor without modification."""



def _call_llm(messages: list) -> str:
    url = f"{settings.DATABRICKS_HOST}/serving-endpoints/{settings.DATABRICKS_LLM_ENDPOINT}/invocations"
    logger.info(f"[LLM] Calling endpoint: {url}")
    t0 = time.time()
    resp = httpx.post(
        url,
        headers={"Authorization": f"Bearer {settings.DATABRICKS_TOKEN}"},
        json={"messages": messages, "max_tokens": 8192, "temperature": 0},
        timeout=120,
    )
    logger.info(f"[LLM] Response received in {time.time() - t0:.1f}s — HTTP {resp.status_code}")
    resp.raise_for_status()
    return resp.json()["choices"][0]["message"]["content"].strip()


def _clean_llm_mquery(raw: str) -> str:
    """Strip accidental markdown fences the LLM may add."""
    raw = re.sub(r"^```[a-zA-Z]*\s*", "", raw.strip(), flags=re.I)
    raw = re.sub(r"\s*```$", "", raw.strip())
    return raw.strip()


def _reconstruct_sql_for_explain(mquery: str) -> str | None:
    """
    Build a concrete SQL string from the M-Query by substituting representative
    values for all dynamic filter variables, so EXPLAIN can validate the SQL shape.

    Substitutions used:
      - dateClause      → AND <col> BETWEEN '2024-01-01' AND '2024-12-31'
      - whereX (list)   → AND <col> IN ('SAMPLE')
      - whereX (single) → AND <col> = 'SAMPLE'
    We resolve these by reading the then-branch of each where* variable.
    """
    # Collect all where*/dateClause variable definitions and their then-values
    var_values: dict[str, str] = {}

    # Match:  varName = \n  if ... then " AND ..." \n  else ""
    for m in re.finditer(
        r'\b(where\w+|dateClause)\s*=\s*\n?\s*if\s+.+?\s+then\s+("(?:[^"\\]|\\.)*")',
        mquery, re.DOTALL
    ):
        var_name  = m.group(1)
        then_val  = m.group(2).strip('"')
        # Replace M string-building expressions like " & combinedlist_X & " with a sample value
        then_val  = re.sub(r'"\s*&\s*\w+\s*&\s*"', "'SAMPLE'", then_val)
        then_val  = re.sub(r'"\s*&\s*[\w.]+\s*\([^)]*\)\s*&\s*"', "'2024-01-01'", then_val)
        var_values[var_name] = then_val

    # Extract the query = "..." multi-segment expression
    query_block = re.search(r'\bquery\s*=\s*\n?([\s\S]+?),\s*\n\s*Source\s*=', mquery)
    if not query_block:
        return None

    block = query_block.group(1)

    # Collect all string literals and variable references in order
    tokens = re.findall(r'"((?:[^"\\]|\\.)*)"|&\s*(\w+)', block)
    parts = []
    for literal, var_ref in tokens:
        if literal:
            parts.append(literal.replace('""', '"'))
        elif var_ref:
            parts.append(var_values.get(var_ref, ""))

    sql = "".join(parts).strip()
    return sql if sql else None


def _execute_explain(sql: str) -> str | None:
    """Run EXPLAIN via SDK StatementExecution. Returns error string if invalid, None if clean."""
    warehouse_id = settings.DATABRICKS_HTTP_PATH.split("/")[-1]
    logger.info(f"[EXPLAIN] Running against warehouse: {warehouse_id}")
    t0 = time.time()
    try:
        client = WorkspaceClient(
            host=settings.DATABRICKS_HOST,
            token=settings.DATABRICKS_TOKEN,
        )
        result = client.statement_execution.execute_statement(
            warehouse_id=warehouse_id,
            statement=f"EXPLAIN {sql}",
            wait_timeout="30s",
        )
        elapsed = time.time() - t0
        state = result.status.state
        logger.info(f"[EXPLAIN] Completed in {elapsed:.1f}s — state: {state}")
        if state in (StatementState.FAILED, StatementState.CANCELED):
            return result.status.error.message
        return None
    except Exception as e:
        logger.error(f"[EXPLAIN] Exception after {time.time() - t0:.1f}s: {e}")
        return str(e)


def fix_mquery_with_llm(mquery: str) -> Tuple[str, str, bool]:
    """
    Send the full M-Query to the LLM for correction.
    After each LLM response, reconstruct a concrete SQL and EXPLAIN-validate it.
    Returns (fixed_mquery, summary, success).
    """
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user",   "content": f"Fix this M-Query:\n\n{mquery}"},
    ]

    current_mquery = mquery
    last_error = ""

    for attempt in range(1, MAX_ATTEMPTS + 1):
        logger.info(f"LLM fix attempt {attempt}/{MAX_ATTEMPTS}")

        try:
            raw = _call_llm(messages)
            current_mquery = _clean_llm_mquery(raw)
            logger.info(f"[LLM] M-Query received, length: {len(current_mquery)} chars")
        except Exception as e:
            logger.error(f"[LLM] Call failed on attempt {attempt}: {e}")
            return current_mquery, f"LLM call failed on attempt {attempt}: {e}", False

        sql_for_explain = _reconstruct_sql_for_explain(current_mquery)
        if not sql_for_explain:
            return current_mquery, "Could not reconstruct SQL from LLM-returned M-Query.", False

        error = _execute_explain(sql_for_explain)

        if error is None:
            summary = f"M-Query validated successfully on attempt {attempt}."
            logger.info(summary)
            return current_mquery, summary, True

        last_error = error
        logger.info(f"Attempt {attempt} EXPLAIN error: {error[:200]}")

        if attempt < MAX_ATTEMPTS:
            messages += [
                {"role": "assistant", "content": current_mquery},
                {"role": "user", "content": (
                    f"The reconstructed SQL from your M-Query still fails Databricks EXPLAIN:\n"
                    f"{error}\n\n"
                    f"Fix the M-Query and return the complete corrected let...in block only."
                )},
            ]

    summary = (
        f"Could not produce valid M-Query after {MAX_ATTEMPTS} attempts. "
        f"Last EXPLAIN error: {last_error}"
    )
    return current_mquery, summary, False


# Keep these for backward compatibility with convert-and-fix endpoint
def fix_sql_with_llm(sql: str) -> Tuple[str, str, bool]:
    """Deprecated: wraps fix_mquery_with_llm for callers that still pass raw SQL."""
    return fix_mquery_with_llm(sql)


def extract_sql_from_mquery(mquery: str) -> str | None:
    return _reconstruct_sql_for_explain(mquery)


def inject_fixed_sql_into_mquery(mquery: str, fixed_sql: str) -> str:
    """No-op shim — LLM now returns the full M-Query directly."""
    return mquery
